# Generated by Django 2.0.3 on 2018-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
