# Generated by Django 2.0.3 on 2018-03-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0002_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
