# Generated by Django 2.0.3 on 2018-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0003_auto_20180310_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=50),
        ),
    ]
