# Generated by Django 2.0.3 on 2018-03-17 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0004_auto_20180310_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plug_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
