# Generated by Django 2.0.3 on 2018-03-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0005_vehicle_plug_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
