# Generated by Django 2.0.3 on 2018-03-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0006_chargeperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('default_start', models.DateTimeField()),
                ('default_end', models.DateTimeField()),
                ('default_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='chargeperiod',
            name='vehicle_id',
        ),
        migrations.AlterField(
            model_name='chargeperiod',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='chargeperiod',
            name='attempt',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='charger.ChargeAttempt'),
            preserve_default=False,
        ),
    ]
