# Generated by Django 2.0.3 on 2018-03-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0007_auto_20180317_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeattempt',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='charger.Owner'),
            preserve_default=False,
        ),
    ]
