# Generated by Django 2.0.3 on 2018-03-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0008_chargeattempt_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargeattempt',
            old_name='vehicle_id',
            new_name='vehicle_name',
        ),
    ]
