# Generated by Django 2.0.3 on 2018-04-08 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0011_auto_20180317_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='unplug_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
